version: "3.9"

services:
  django_app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/staticfiles
    env_file:
      - .env
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./nginx
    restart: always
    depends_on:
      - django_app
    ports:
      - 80:80
      - 443:443
    volumes:
      -  static-data:/app/staticfiles
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      #CREATED THE SAME VOLUME FOR BOTH CERTBOT AND NGINX, SO THEY BOTH HAVE ACCESS TO THE SSL CERTIFICATE
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot


#THIS WILL RUN CERBOT TO GET YOU AN SSL CERT FOR YOUR DOMAIN. SET THIS CONFIGURATION ON THE DEPLOYMENT SERVER BEFORE RUNING DOCKER BUILD AND DOCKER UP
  certbot:
    image: certbot/certbot:latest
    volumes:
    #THIS CREATE A VOLUME ON LOCAL ENV AND ATTACHED IT TO THE DOCKER CONTAINER 
      - ./data/certbot/conf:/etc/letsencrypt 
      - ./data/certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email {your email} -d {your domain name} --agree-tos

volumes:
  static-data: