version: "3.9"

services:
  django_app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/staticfiles
    env_file:
      - .env
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./nginx
    restart: always
    depends_on:
      - django_app
    ports:
      - 80:80
    volumes:
      - static-data:/app/staticfiles

volumes:
  static-data: