version: "3.9"

services:
  django_app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/staticfiles
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  nginx:
    build:
      context: ./nginx
    restart: always
    depends_on:
      - django_app
    ports:
      - 80:80
    volumes:
      - static-data:/staticfiles

volumes:
  postgres-data:
  static-data: